version: '3.8'

services:
  task-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    ports:
      - "5000:5000"
    networks:
      - keploy-network

networks:
  keploy-network:
    driver: bridge
