name: Keploy API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry (optional if needed)
      if: false # set to true and configure secrets if using private containers
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image for the App
      run: docker build -t task-manager-app .

    - name: Create Docker Network
      run: docker network create keploy-network

    - name: Run App Container
      run: |
        docker run -d \
          --name task-app \
          --network keploy-network \
          task-manager-app

    - name: Run Keploy Tests
      run: |
        docker run --rm \
          --network keploy-network \
          -v ${{ github.workspace }}:/app \
          -w /app \
          ghcr.io/keploy/keploy:v2.6.12 \
          test \
          -c "python app.py" \
          --cmd-type native \
          --container-name task-app \
          --network-name keploy-network \
          --build-delay 30 \
          --delay 10

    - name: Upload Keploy Test Report (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: keploy-test-report
        path: |
          keploy/testReports/
          keploy-logs.txt
          Keploy_Test_Report*.png
